jobs:
  - script: >
        pipelineJob('curl-build'){
          displayName('curl-build')
        definition {
            cps {
                sandbox()
                script(''' 
          node('curl-builder') {
                  stage('Workspace files') { sh 'ls' }
                  stage('Checkout') { checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/curl/curl.git']]) }
                  stage('autoreconf -fi') { sh 'autoreconf -fi' }
                  stage('./configure --without-ssl') { sh './configure --without-ssl' }
                  stage('make') { sh 'make' }
                  stage('make test') { sh 'make check > test-output.log' }
                  stage('Archive test log') { archiveArtifacts artifacts: 'test-output.log', allowEmptyArchive: true }
                  stage('make install') { sh 'make install' }
                  stage('Archive executable') { archiveArtifacts allowEmptyArchive: true, artifacts: 'src/curl , src/.libs/*', fingerprint: true, followSymlinks: false, onlyIfSuccessful: true }
              }      
              ''')
            }
        }
        }
